### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by rakibhossain3574** [ErdiBgr/Countfect#1]
Please add timing property because counterup time is more than 1s.

**Comment by ErdiBgr** [comment]
**Hey I added the delay feature at your request. Good work. :) **
# For example
```html
<h1 class="countfect" delay="5000" data-num="36000"></h1>
```

**Comment by ErdiBgr** [comment]
**Hey I added the delay feature at your request. Good work. :)**
# For example
```html
<h1 class="countfect" delay="5000" data-num="36000"></h1>
```
