### ISSUE TITLE
I need to update counter AFTER page load not before... Is there a way to do that?

### ISSUE THREAD

**Issue by inglesuniversal** [ErdiBgr/Countfect#2]
This is the code I am trying to feed into Countfect ... it gets refreshed as page loads images using a simple loop NUM++

`$('#tracks').html("<span class="countfect" delay="50000" data-num="${track}" style="color:#00b8ff;font-weight:900;font-size:40px;font-family: sans-serif;"></span>");`

Is it possible to accomplish that?

**Comment by ErdiBgr** [comment]
**Hey If you want the Countfect to run after the page loads, you can use the following code block. **
```js
$(document).load(function () {
 $('#tracks').html("<span class="countfect" delay="50000" data-num="${track}" style="color:#00b8ff;font-weight:900;font-size:40px;font-family: sans-serif;"></span>");
});
```
